version: '3'
services:
  backend:
    container_name: screening-test-backend
    restart: always
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./run.py
      PYTHONUNBUFFERED: 1
    image: screening-test-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/backend

  jenkins:
    container_name: jenkins-blueocean
    build:
      context: jenkins
      dockerfile: Dockerfile
    user: root
    image: jenkins-blueocean
    ports:
      - '5001:8080'
      - '5002:8443'
    volumes:
      - ./jenkins/jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME:/home
