version: '3'
services:
  backend:
    container_name: screening-test-backend
    restart: always
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./run.py
      PYTHONUNBUFFERED: 1
    image: screening-test-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/backend
